[package]
name = "mojo-lsp-server"
version = "0.1.0"
authors = ["The Chromium Authors"]
edition = "2018"

[dependencies]
lsp-types = "0.55"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
